app:
  name: ui
  image:
    repository: 'onecx<% if(standalone){ %>-standalone<% } %>/<%= fileName %>-ui'
  routing:
    enabled: true
    path: /mfe/<%= propertyName %>/
<% if(!standalone){ %>  
  operator:
    # Microfrontend
    microfrontend:
      enabled: true
      specs:
        exposedModule: "./<%= remoteModuleName %>Module"
        description: "OneCX <%= remoteModuleName %> Module"
        note: "OneCX <%= remoteModuleName %> UI module auto import via MF operator"
        type: MODULE
    # Permission
    permission:
      enabled: true
      spec:
        permissions:
    # Keycloak
    keycloak:
      client:
        enabled: true
        spec:
          kcConfig:
            clientId: "<%= fileName %>-ui"

# PIPE Config
<% } %>